Namespace Win32.TaskScheduler.V1

	Friend Enum TASK_TRIGGER_TYPE As UInt32
		ONCE = 0UI
		DAILY = 1UI
		WEEKLY = 2UI
		MONTHLYDATE = 3UI
		MONTHLYDOW = 4UI
		ON_IDLE = 5UI
		AT_SYSTEMSTART = 6UI
		AT_LOGON = 7UI
	End Enum

	Friend Enum TASKPAGE As UInt16
		TASKPAGE_TASK = 0UI
		TASKPAGE_SCHEDULE = 1UI
		TASKPAGE_SETTINGS = 2UI
	End Enum

End Namespace